import React, { useState } from 'react';
import { SurveyData } from '../types';
import { ClipboardCheck, Download, Send } from 'lucide-react';

interface Props {
  onSubmit: (data: SurveyData) => void;
}

export const SurveyForm: React.FC<Props> = ({ onSubmit }) => {
  const [formData, setFormData] = useState<Partial<SurveyData>>({});

  const handleChange = (key: keyof SurveyData, value: string | number) => {
    setFormData(prev => ({ ...prev, [key]: value }));
  };

  const isComplete = 
    formData.q1_easyStart &&
    formData.q2_clearExplanation &&
    formData.q3_personalized &&
    formData.q4_usefulSkills &&
    formData.q5_helpfulSwot &&
    formData.q6_clearGoals &&
    formData.q7_easyProgress &&
    formData.q8_motivated &&
    formData.q9_aiFeedbackHelpful &&
    formData.q10_deviceEasy &&
    formData.q11_designHelpful &&
    formData.q12_recommend &&
    formData.q13_feedback;

  const renderRating = (key: keyof SurveyData, label: string, lowText: string, highText: string) => (
    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
      <label className="block text-lg font-bold text-arden-navy mb-4">{label}</label>
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
        <span className="text-sm text-gray-500 font-medium w-24 text-right sm:text-left">{lowText}</span>
        <div className="flex gap-4">
          {[1, 2, 3, 4, 5].map(num => (
            <button
              key={num}
              onClick={() => handleChange(key, num)}
              className={`w-12 h-12 rounded-full font-bold text-lg transition-all ${
                formData[key] === num 
                  ? 'bg-arden-teal text-white ring-4 ring-teal-100 scale-110' 
                  : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
              }`}
            >
              {num}
            </button>
          ))}
        </div>
        <span className="text-sm text-gray-500 font-medium w-24">{highText}</span>
      </div>
    </div>
  );

  const renderYesNo = (key: keyof SurveyData, label: string) => (
    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
      <label className="block text-lg font-bold text-arden-navy mb-4">{label}</label>
      <div className="flex gap-4">
        {['Yes', 'No'].map(opt => (
          <button
            key={opt}
            onClick={() => handleChange(key, opt)}
            className={`flex-1 py-3 px-6 rounded-lg font-bold transition-all ${
              formData[key] === opt
                ? opt === 'Yes' ? 'bg-green-100 text-green-800 border-2 border-green-500' : 'bg-red-100 text-red-800 border-2 border-red-500'
                : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
            }`}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );

  const renderText = (key: keyof SurveyData, label: string) => (
    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
      <label className="block text-lg font-bold text-arden-navy mb-4">{label}</label>
      <textarea
        value={formData[key] as string || ''}
        onChange={(e) => handleChange(key, e.target.value)}
        rows={3}
        className="w-full p-4 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-arden-teal outline-none"
        placeholder="Type your answer here..."
      />
    </div>
  );

  return (
    <div className="max-w-4xl mx-auto pb-20 animate-fade-in">
      <div className="text-center mb-10">
        <div className="bg-arden-navy w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 text-white shadow-lg">
            <ClipboardCheck size={32} />
        </div>
        <h2 className="text-4xl font-bold text-arden-navy font-serif mb-3">Feedback Survey</h2>
        <p className="text-xl text-arden-grey">Complete this short survey to download your full Personal Development Plan.</p>
      </div>

      <div className="space-y-6">
        {renderRating('q1_easyStart', '1. How easy was it for you to get started with the app?', 'Very Difficult', 'Very Easy')}
        
        {renderYesNo('q2_clearExplanation', '2. Did the app clearly explain what you need to do in each step?')}
        
        {renderYesNo('q3_personalized', '3. Did the app feel personalized to you based on your goals or skills?')}
        
        {renderRating('q4_usefulSkills', '4. How useful were the career skills and suggestions provided by the app?', 'Not Useful', 'Very Useful')}
        
        {renderYesNo('q5_helpfulSwot', '5. Did you feel the app gave you helpful advice about your strengths, weaknesses, opportunities, and threats (SWOT)?')}
        
        {renderYesNo('q6_clearGoals', '6. Were the goals generated by the app clear and easy to understand?')}
        
        {renderRating('q7_easyProgress', '7. How easy was it to see your progress while using the app?', 'Very Difficult', 'Very Easy')}
        
        {renderText('q8_motivated', '8. Did you feel motivated to complete the steps in the app? Why or why not?')}
        
        {renderYesNo('q9_aiFeedbackHelpful', '9. Did the AI’s feedback (like SMART goals) help you better understand how to achieve your personal goals?')}
        
        {renderYesNo('q10_deviceEasy', '10. Was the app easy to use on your device?')}
        
        {renderRating('q11_designHelpful', '11. How helpful was the app’s design and layout?', 'Not Helpful', 'Very Helpful')}
        
        {renderText('q12_recommend', '12. Would you recommend this app to a friend who wants to plan their career? Why or why not?')}
        
        {renderText('q13_feedback', '13. Do you have any feedback, suggestions, or comments?')}
      </div>

      <div className="mt-12 text-center">
        <button
          onClick={() => isComplete && onSubmit(formData as SurveyData)}
          disabled={!isComplete}
          className={`px-10 py-5 rounded-2xl font-bold text-xl shadow-xl flex items-center gap-3 mx-auto transition-transform hover:-translate-y-1
            ${isComplete 
              ? 'bg-arden-teal text-white hover:bg-teal-500' 
              : 'bg-gray-300 text-gray-500 cursor-not-allowed'
            }`}
        >
          {isComplete ? (
            <>
              Submit & Download Data <Download size={24} />
            </>
          ) : (
            'Complete all questions to Finish'
          )}
        </button>
        {!isComplete && (
           <p className="mt-4 text-red-400 font-medium">Please answer all 13 questions to unlock your download.</p>
        )}
      </div>
    </div>
  );
};